name: Python Linter

on:
  pull_request:
    paths:
      - '**/*.pyw'  # Specify the path pattern for your Python files

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # Install the linter of your choice (e.g., flake8)

      - name: Run linter
        run: |
          flake8 .  # Run the linter on all Python files in the repository